language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
  password:
    secure: QJxH1m3GMpgeN3AzO3fKap8qZlJSAzGE7bBgXmwnqHabr/wmecTp8Nn7amrfZ81LqyqX2NKseTAugGV/F+PhMC1Xp03aO7U4ppn7/9pBtRk/tGsoy/acfRG78NbmWonUsApbpRlw02/4rocppo2qnnjj/Q+cPqmQhovux6tkpeLdpItWuKuXfPI745vxYGABmtwZGwd59TmWP0PR1Fhuz9IiA0JUo1P4d4DB5ltw1qdAT43Nmzz4/S5mMDpnr54yfa+L7NSNy0q4U6mpvHXM62l7mrQP6P6qOH4W+HKYsS9jiMhmCT7zLbug+k77BwuHiiBy+E+i7pPFHwHqze8+T980nsFPtnae/iT338JYDFHxkEe0GBF08brXA2YRkN9h57b4dIhGH3eNt+eDTXz8BIC/6oUivwVjvilZTpK89DTItGSpBz7NSMB+ByooNqbLJzK8eTpepRyv4FCfbO6Wh2mv1JIU7bFkejpJoI3hVpOk3hhS8iKT+CCB01cyDAJqOiGqQ14ZtGljKqIxPGWwjnLVi1wPUBssuByFYGq302t7DZYC1kSwBltJG3kFgffFWCAIIOAv0lS51N28u1+jN5nALCT5yI0omzLeERC4Bo/rZXcOtuvOh/ebXYLeFLkUYgsTz7JFPhKZOB1BL2QNWNYwwTp1YVZYW+eODubCOT8=
