# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check licenses

on:
  push:
    branches: [ "dataengine-poc", "main" ]
    paths:
    - setup.py
    - requirements*.txt
  pull_request:
    branches: [ "dataengine-poc", "main" ]
    paths:
    - setup.py
    - requirements*.txt

jobs:
  check-licenses:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dagshub/python-license-checker-action@v1
